### ISSUE TITLE
Acropolis installation does not configure smtp

### ISSUE THREAD

**Issue by tetchey** [YunoHost-Apps/acropolis_ynh#49]
### Describe the bug

Acropolis for Yunohost installs correctly, however the SMTP parameters are not enabled or configured. As a result, the default installation becomes unusable unless SMTP is manually configured in the `defaults.yml` file.

As an email confirmation is sent when a user creates an account and the account is not able to be used until the email is actioned, it is reasonable to assume that the Acropolis installer should configure SMTP by default if possible.

### Context

- Hardware: VPS with 2GB RAM, 2 CPUs, 32GB HDD.
- YunoHost version: 11.0.10.2 (stable).
- I have access to my server: Through SSH, webadmin and virtual console.
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no
- Using, or trying to install package version/branch: 2022.01.29~ynh1

### Steps to reproduce

- From Admin GUI. Applications > Install > Acropolis
- From the Acropolis application GUI, sign up as a new user
- No email confirmation is received, so account cannot be used

### Expected behavior

I would expect that the installation process configure the Acropolis SMTP settings to relay via the default SMTP server of the Yunohost installation. 

### Default configuration

The default mail configuration per the installation (lines 157 to 173 of `/var/www/acropolis/config/defaults.yml`) is:

```yaml
  mail:
    enable: false
    sender_address: 'no-reply@example.org'
    method: 'smtp'
    smtp:
      host: 'localhost'
      port: 587
      authentication: 'plain'
      username:
      password:
      starttls_auto: true
      openssl_verify_mode:
      domain:
    sendmail:
      location: '/usr/sbin/sendmail'
      exim_fix: false
    message_bus_api_key:
```

### Additional

I am unsure how this is supposed to be configured, or if it is even possible for the installer to perform this task. I have attempted changing `enable: false` to `enable: true` in addition to various username and password combinations, all unsuccessfully.

Also, the Acropolis Documentation link on https://yunohost.org/en/apps is either broken or the documentation is non-existent,  making it difficult to know how to complete this part of the installation.

Any assistance getting the SMTP settings configured by the installer and/or information on how to perform this step manually would be greatly appreciated.
